name: Node.js Build-Sign-Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-sign-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t saivenkatvaraprasady/jenkin-node-app .
      - name: Install Cosign
        run: |
          curl -Lo cosign https://artifacts.sigstore.dev/cosign/v2.2.4/cosign-linux-amd64
          chmod +x cosign
          sudo mv cosign /usr/local/bin/
      - name: Generate Cosign Key
        run: |
          cosign generate-key-pair
      - name: Sign Docker image
        run: |
          cosign sign --key cosign.key saivenkatvaraprasady/jenkin-node-app
      - name: Push Docker image
        run: |
          docker push saivenkatvaraprasady/jenkin-node-app
